"""followers

Revision ID: 1615e2cf2a79
Revises: 71c69a811426
Create Date: 2023-05-15 16:54:27.417702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1615e2cf2a79'
down_revision = '71c69a811426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
