"""add language to post

Revision ID: 2270dd6b283a
Revises: 1615e2cf2a79
Create Date: 2023-05-19 14:26:12.733918

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2270dd6b283a'
down_revision = '1615e2cf2a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
