"""new fields in user model

Revision ID: 71c69a811426
Revises: 4aac87702d74
Create Date: 2023-05-15 10:16:03.415905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71c69a811426'
down_revision = '4aac87702d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
